<?php

/*
 * Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

use Drupal\ckeditor5_plugin_pack\Utility\LibraryDefinitionItem;

/**
 * @param array $libraries
 * @return array
 */
function ckeditor5_plugin_pack_library_loader(array $libraries): array {
  /** @var \Drupal\ckeditor5_plugin_pack\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_plugin_pack.config_handler.settings');
  $definitions = [];
  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $config_handler->isLocalLibraryPathSpecified()
      ? $definition->addLocalJs($definition->id())
      : $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;
}
