<?php

/*
 * Copyright (c) 2003-2024, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types=1);

use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_plugin_pack_todo_document_list_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  if (isset($plugin_definitions['ckeditor5_plugin_pack_todo_document_list__todo_document_list']) && !\Drupal::service('ckeditor5_plugin_pack.core_library_version_checker')->isLibraryVersionHigherOrEqual('41.0.0')) {
    $plugin = $plugin_definitions['ckeditor5_plugin_pack_todo_document_list__todo_document_list'];

    $definition = $plugin->toArray();
    $definition['ckeditor5']['plugins'] = ['list.TodoDocumentList'];

    $pluginDefinition = new CKEditor5PluginDefinition($definition);
    $plugin_definitions['ckeditor5_plugin_pack_todo_document_list__todo_document_list'] = $pluginDefinition;
  }
}
